kind: Service
apiVersion: v1
metadata:
  name: mysql 
  namespace: expense
spec: 
  selector:
    app: mysql 
    tier: mysql 
    purpose: expense  
  ports:
  - protocol: TCP
    port: 3306 #service port
    targetPort: 3306